name: Typescript & lint

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Lint
        run: yarn lint

      - name: Typescript
        run: yarn typescript
